name: flutter_tutorial_screenshot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  # Take Screenshot
  screenshot: ^3.0.0

  # Save Screenshot
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1

  # Save and Share Screenshot
  share_plus: ^9.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

